version: "3"

services:
  backend:
    container_name: practice-backend
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      DB_URL: postgresql:5432/leti_practice
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  postgresql:
    container_name: practice-database
    image: "postgres:14"
    environment:
      POSTGRES_DB: leti_practice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5460:5432"
