logging:
  level:
    web: INFO
    org.apache.pdfbox: INFO
    org.apache.fontbox: INFO
    com.mayosen.letipractice: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

  mvc:
    log-request-details: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
